apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ include "sb.fullname" . }}-pv
  labels:
    {{- include "sb.labels" . | nindent 4 }}
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  csi:
    driver: {{ $.Values.db.nfs.nfsProvisioner }}
    volumeHandle: "{{ $.Values.db.nfs.volumeHandlePrefix }}.{{ include "sb.fullname" . }}"
    volumeAttributes:
      server: {{ $.Values.db.nfs.server }}
      share: "{{ $.Values.db.nfs.share }}/{{ include "sb.fullname" . }}"
