apiVersion: v1
kind: Secret
metadata:
  name: {{ include "sb.name" . }}-chap-secret
type: "kubernetes.io/iscsi-chap"
data:
  node.session.auth.username: {{ .Values.db.iscsiChap.initiatorName | b64enc }}
  node.session.auth.password: {{ .Values.db.iscsiChap.cred.initiator | b64enc }}
  node.session.auth.username_in: {{ .Values.db.iscsiChap.targetName | b64enc }}
  node.session.auth.password_in: {{ .Values.db.iscsiChap.cred.target | b64enc }}