services:
  db:
    image: mysql:9.2.0-oracle
    platform: linux/arm64
    environment:
      MYSQL_ROOT_PASSWORD: 'password'
      MYSQL_DATABASE: 'sb'
      MYSQL_USER: 'docker'
      MYSQL_PASSWORD: 'password!'
    ports:
      - "3308:3306"
  api:
    hostname: app
    restart: unless-stopped
    image: sb-api
    platform: linux/arm64
    depends_on:
      - db
    ports:
      - "50052:50052"
  currency:
    hostname: currency
    restart: unless-stopped
    image: sb-currency
    platform: linux/arm64
    ports:
      - "9002:9002"
  migrator:
    image: sb-api
    depends_on:
      - db
    environment:
      MIGRATOR: 'true'
  auth:
    hostname: auth
    restart: unless-stopped
    image: sb-auth
    platform: linux/arm64
    depends_on:
      - db
    ports:
      - "50051:50051"
  gateway:
    hostname: gateway
    restart: unless-stopped
    image: api-gateway
    platform: linux/arm64
    depends_on:
      - auth
      - api
    ports:
      - "8080:3000"
  ui:
    depends_on:
      - db
    image: sb-ui

