services:
  db:
    volumes:
      - data:/var/lib/mysql
  
  api:
    build:
      target: dev
      context: api
      dockerfile: Dockerfile.grpc
    volumes:
      - ./api:/app
      - ./config/api:/app/envs
    working_dir: /app
  
  currency:
    build:
      context: currency
      dockerfile: Dockerfile
    volumes:
      - ./config/currency:/app/config
    working_dir: /app
    environment:
      EXC_TOKEN: ${EXC_TOKEN}
      ENV: dev

  migrator:
    volumes:
      - ./api:/app
      - ./config/api/:/app/envs
    working_dir: /app
  
  auth:
    build:
      target: dev
      context: auth
      dockerfile: Dockerfile.grpc
    volumes:
      - ./auth:/app
      - ./config/auth/:/app/envs
    working_dir: /app
  
  gateway:
    build:
      target: dev
      context: api-gateway
      dockerfile: Dockerfile.grpc
    volumes:
      - ./api-gateway:/app
      - ./config/gateway/:/app/envs
    working_dir: /app
  
  ui:
    build:
      context: ui
      target: dev
    ports:
      - "4202:4202"
    develop:
      watch:
        - action: sync
          path: ./ui
          target: /app
        - action: rebuild
          path: package.json
volumes:
  data:
