services:
  db:
    volumes:
      - data:/var/lib/mysql
  api:
    image: "ghcr.io/bdarge/sb-api:0.2.0"
    volumes:
      - ./api/envs:/app/envs
      - ./scripts:/app/scripts
    command: >
      sh -c "/app/scripts/wait-for-it.sh 127.0.0.1:3308 -- /app/api"
  migrator:
    image: "ghcr.io/bdarge/sb-api:0.2.0"
    volumes:
      - ./api/db:/app/db
      - ./api/envs:/app/envs
      - ./scripts:/app/scripts
  gateway:
    image: "ghcr.io/bdarge/sb-api-gateway:0.1.2"
    volumes:
      - ./gateway/envs:/app/envs
      - ./scripts:/app/scripts
    environment:
      GIN_MODE: release
    command: >
      sh -c "/app/scripts/wait-for-it.sh 127.0.0.1:3308 -- /app/gateway"
  auth:
    image: "ghcr.io/bdarge/sb-auth:1.1.0"
    volumes:
      - ./auth/envs:/app/envs
      - ./scripts:/app/scripts
    command: >
      sh -c "/app/scripts/wait-for-it.sh 127.0.0.1:3308 -- /app/auth"
  ui:
    image: "ghcr.io/bdarge/sb-ui:0.3.0"
    environment:
      ENVIRONMENT: prod
    ports:
      - "4202:80"
volumes:
  data: {}
