version: "3.9"

services:
  db:
    image: arm64v8/mysql
    platform: linux/arm64
    cap_add:
      - SYS_NICE
    # use the old authentication protocol, so I can use the popular mysql nodejs package
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: 'password'
      MYSQL_DATABASE: 'sb'
      MYSQL_USER: 'docker'
      MYSQL_PASSWORD: 'password!'
    ports:
      - "3308:3306"
    volumes:
      - data:/var/lib/mysql
  api:
    hostname: app
    restart: unless-stopped
    image: api
    platform: linux/arm64
    depends_on:
      - db
    build:
      context: api
      target: dev
      dockerfile: Dockerfile.grpc
    working_dir: /app
    volumes:
      - ./api:/app
      - ./config/api:/app/envs
    ports:
      - "50052:50052"
    command: >
      sh -c "wait-for-it.sh 127.0.0.1:3308 -- /app/api"
  migrator:
    image: api
    depends_on:
      - db
    build:
      context: api
      dockerfile: Dockerfile.grpc
      target: dev_migrator
    volumes:
      - ./api:/app
      - ./misc:/misc
      - ./config/api/:/app/envs
    working_dir: /app
    environment:
      MIGRATOR: 'true'
    command: >
      sh -c "wait-for-it.sh 127.0.0.1:3308 -- /app/api"
  auth:
    hostname: auth
    restart: unless-stopped
    image: auth
    platform: linux/arm64
    depends_on:
      - db
    build:
      context: auth
      target: dev
      dockerfile: Dockerfile.grpc
    volumes:
      - ./auth:/app
      - ./config/auth/:/app/envs
    working_dir: /app
    ports:
      - "50051:50051"
    command: >
      sh -c "wait-for-it.sh 127.0.0.1:3308 -- /app/api"
  gateway:
    hostname: gateway
    restart: unless-stopped
    image: api-gateway
    platform: linux/arm64
    depends_on:
      - auth
      - api
    build:
      context: api-gateway
      target: dev
      dockerfile: Dockerfile.grpc
    volumes:
      - ./api-gateway:/app
      - ./config/gateway/:/app/envs
    working_dir: /app
    ports:
      - "3000:3000"
volumes:
  data: {}