version: "3.9"

services:
  db:
    image: arm64v8/mysql
    platform: linux/arm64
    cap_add:
      - SYS_NICE
    # use the old authentication protocol, so I can use the popular mysql nodejs package
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: 'password'
      MYSQL_DATABASE: 'sb'
      MYSQL_USER: 'docker'
      MYSQL_PASSWORD: 'password!'
    ports:
      - "3308:3306"
  api:
    hostname: app
    restart: unless-stopped
    image: sb-api
    platform: linux/arm64
    depends_on:
      - db
    ports:
      - "50052:50052"
    command: >
      sh -c "/misc/wait-for-it.sh 127.0.0.1:3308 -- /app/api"
  migrator:
    image: sb-api
    depends_on:
      - db
    environment:
      MIGRATOR: 'true'
    command: >
      sh -c "/misc/wait-for-it.sh 127.0.0.1:3308 -- /app/api"
  auth:
    hostname: auth
    restart: unless-stopped
    image: sb-auth
    platform: linux/arm64
    depends_on:
      - db
    ports:
      - "50051:50051"
    command: >
      sh -c "/misc/wait-for-it.sh 127.0.0.1:3308 -- /app/auth"
  gateway:
    hostname: gateway
    restart: unless-stopped
    image: api-gateway
    platform: linux/arm64
    depends_on:
      - auth
      - api
    ports:
      - "3000:3000"
    command: >
      sh -c "/misc/wait-for-it.sh 127.0.0.1:3308 -- /app/gateway"
  ui:
    depends_on:
      - db
    image: sb-ui


