version: "3.9"

services:
  db:
    volumes:
      - data:/var/lib/mysql
  api:
    image: "ghcr.io/bdarge/sb-api:0.0.1-alpha"
    volumes:
      - ./config/api/:/app/envs
      - ./misc:/misc
  migrator:
    image: "ghcr.io/bdarge/sb-api:0.0.1-alpha"
    volumes:
      - ./api/db:/app/db
      - ./config/api/:/app/envs
      - ./misc:/misc
  gateway:
    image: "api-gateway-0.0.3"
    volumes:
      - ./config/gateway/:/app/envs
      - ./misc:/misc
    environment:
      GIN_MODE: release
  auth:
    image: "ghcr.io/bdarge/sb-auth:0.0.1-alpha"
    volumes:
      - ./config/auth/:/app/envs
      - ./misc:/misc
  ui:
    image: "ui-0.0.3"
    environment:
      ENVIRONMENT: prod
#    volumes:
#      - ${PWD}/ui/ssl/:/etc/nginx/certs
#      - ${PWD}/ui/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    ports:
      - "4201:80"
volumes:
  data: {}
