apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: sb-ca-tsl
spec:
  duration: 2160h # 90d
  renewBefore: 360h # 15d
  subject:
    organizations:
      - {{ include "sb.fullname" . }}
  privateKey:
    algorithm: RSA
    encoding: PKCS1
    size: 2048
  dnsNames: {{ .Values.app.domain }}
  secretName: sb-ca-tsl
  issuerRef:
    name: ca-issuer
    kind: Issuer
    group: cert-manager.io
