apiVersion: v1
kind: Secret
metadata:
  name: {{ include "sb.name" . }}-secret
data:
  MYSQL_USER_PWD: {{ .Values.db.mainDb.cred.user | toString | b64enc | quote }}
  MYSQL_ROOT_PWD: {{ .Values.db.mainDb.cred.root | toString | b64enc | quote }}