apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "sb.fullname" . }}-api-config
  annotations:
    "kubernetes.io/service-account.name": {{ include "sb.serviceAccountName" . }}
data:
  prod.env: |
    DB_PORT={{ .Values.db.service.port }}
    DB_SVC="{{ include "sb.fullname" . }}-db-svc"
    PORT=":{{ .Values.api.service.targetPort }}"
    MIGRATION_DIR={{ .Values.migration.migrationPath | quote }}
    DATABASE={{ .Values.db.db_name | quote }}
