apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "sb.fullname" . }}-api-config
  annotations:
    "kubernetes.io/service-account.name": {{ include "sb.serviceAccountName" . }}
data:
  prod.env: |
    DSN="{{ .Values.db.mainDb.user }}:{{ .Values.db.mainDb.cred.user }}@tcp({{ include "sb.fullname" . }}-db-svc:{{ .Values.db.service.port }})/{{ .Values.db.mainDb.database }}?parseTime=true"
    PORT=":{{ .Values.api.service.targetPort }}"
    MIGRATION_DIR={{ .Values.migration.migrationPath | quote }}
    DATABASE={{ .Values.db.mainDb.database | quote }}
