apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "sb.fullname" . }}-migration-job
  labels:
    {{- include "sb.labels" . | nindent 4 }}
spec:
  backoffLimit: 0
  template:
    metadata:
      {{- with .Values.api.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "sb.labels" . | nindent 8 }}
        app: {{ template "sb.name" . }}-api
    spec:
      {{- with .Values.imagePullSecrets.ghcr }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "sb.serviceAccountName" . }}
      dnsPolicy: {{ .Values.dnsPolicy }}
      initContainers:
        - name: wait-for-mysql
          image: busybox:latest
          imagePullPolicy: IfNotPresent
          command: ['sh', '-c', 'until nc -vz ${SVC_NAME} 3308; do echo "Waiting for mysql db..."; sleep 3; done;']
          env:
            - name: SVC_NAME
              value: {{ include "sb.fullname" . }}-db-svc
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.migration.image.repository }}:{{ .Values.migration.image.tag | default .Chart.AppVersion }}"
          command: ["/bin/bash"]
          args:
            - "-c"
            - >-
              git clone --single-branch --branch {{ .Values.migration.branch }} {{ .Values.migration.repoUrl }} &&
                /app/api
          env:
            - name: ENV
              value: "prod"
            - name: MIGRATOR
              value: "true"
            - name: GIT_TOKEN
              valueFrom:
                secretKeyRef:
                  name: {{ include "sb.name" . }}-git-secret
                  key: GIT_TOKEN
          volumeMounts:
            - name: config
              mountPath: "/app/envs"
      volumes:
        - name: config
          configMap:
            name: {{ include "sb.fullname" . }}-api-config
            items:
            - key: "prod.env"
              path: "prod.env"
      restartPolicy: {{ .Values.migration.job.restartPolicy }}
      dnsConfig:
        options:
          - name: ndots
            value: {{ .Values.dnsConfig.ndots | quote }}