apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultDynamicSecret
metadata:
  name: vso-db
  namespace: sb-app
  annotations:
    sb.config/mysql-host: sb-db-svc:3308
spec:

  # Mount path of the secrets backend
  mount: sb-db

  # Path to the secret
  path: creds/sb-mysql-role

  # Where to store the secrets
  destination:
    create: true
    name: sb-db
    transformation:
      excludes:
       - .*
      templates:
        dns:
          text: |
            {{- $host := get .Annotations "sb.config/mysql-host" -}}
            {{- printf "DSN=%s:%s@tcp(%s)/profile?parseTime=true" (get .Secrets "username") (get .Secrets "password") $host -}}

  # Restart these pods when secrets rotated
  # rolloutRestartTargets:
  # - kind: Deployment
  #   name: sb-auth

  # Name of the CRD to authenticate to Vault
  vaultAuthRef: vso-auth-dynamic
