apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: vso-registry
  namespace: sb-app
spec:
  type: kv-v2

  # mount path
  mount: kvv2

  # path of the secret
  path: sb-app/ghcr

  # dest k8s secret
  destination:
    name: ghcr
    type: kubernetes.io/dockerconfigjson
    create: true

  # static secret refresh interval
  refreshAfter: 30s

  # Name of the CRD to authenticate to Vault
  vaultAuthRef: vso-k8s-auth
---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: vso-db-root
  namespace: sb-app
spec:
  type: kv-v2

  # mount path
  mount: kvv2

  # path of the secret
  path: sb-app/db-root

  # dest k8s secret
  destination:
    name: db-root-secret
    create: true

  # static secret refresh interval
  refreshAfter: 30s

  # Name of the CRD to authenticate to Vault
  vaultAuthRef: vso-k8s-auth
---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: vso-jwt
  namespace: sb-app
spec:
  type: kv-v2

  # mount path
  mount: kvv2

  # path of the secret
  path: sb-app/jwt-key

  # dest k8s secret
  destination:
    name: sb-jwt-key
    create: true

  # static secret refresh interval
  refreshAfter: 30s

  # Name of the CRD to authenticate to Vault
  vaultAuthRef: vso-k8s-auth
---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: vso-cloudflare-api-token
  namespace: sb-app
spec:
  type: kv-v2

  # mount path
  mount: kvv2

  # path of the secret
  path: sb-app/cloudflare-api-token

  # dest k8s secret
  destination:
    name: cloudflare-api-token
    create: true

  # static secret refresh interval
  refreshAfter: 30s

  # Name of the CRD to authenticate to Vault
  vaultAuthRef: vso-k8s-auth
---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: vso-currency-key
  namespace: sb-app
spec:
  type: kv-v2

  # mount path
  mount: kvv2

  # path of the secret
  path: sb-app/exc-token

  # dest k8s secret
  destination:
    name: sb-currency
    create: true

  # static secret refresh interval
  refreshAfter: 30s

  # Name of the CRD to authenticate to Vault
  vaultAuthRef: vso-k8s-auth
