apiVersion: v1
kind: ServiceAccount
metadata:
  namespace: sb-app
  name: sb-sa
---
apiVersion: v1
kind: ServiceAccount
metadata:
  # SA bound to the VSO namespace for transit engine auth
  namespace: vault-secrets-operator-system
  name: vso-operator-sa
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: role-tokenreview-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: system:auth-delegator
subjects:
- kind: ServiceAccount
  name: sb-sa
  namespace: sb-app
- kind: ServiceAccount
  name: vso-operator-sa
  namespace: vault-secrets-operator-system
---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultConnection
metadata:
  namespace: sb-app
  name: vault-connection
spec:
  address: "https://192.168.50.76:8200"
  skipTLSVerify: true
---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultAuth
metadata:
  name: vso-auth
  namespace: sb-app
spec:
  vaultConnectionRef: vault-connection
  method: kubernetes
  mount: k8s
  kubernetes:
    role: sb-role
    serviceAccount: sb-sa
    # audiences:
    #   - vault
---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultAuth
metadata:
  name: vso-auth-dynamic
  namespace: sb-app
spec:
  vaultConnectionRef: vault-connection
  method: kubernetes
  mount: k8s
  kubernetes:
    role: auth-role
    serviceAccount: sb-sa
    # audiences:
    #   - vault
