apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "sb.fullname" . }}-api-gw-config
  annotations:
    "kubernetes.io/service-account.name": {{ include "sb.serviceAccountName" . }}
data:
  prod.env: |
    PORT=":{{ .Values.apiGateway.service.targetPort }}"
    AUTH_SVC_URL="{{ include "sb.fullname" . }}-auth-svc:{{ .Values.auth.service.targetPort }}"
    API_SVC_URL="{{ include "sb.fullname" . }}-api-svc:{{ .Values.api.service.targetPort }}"
    BASE_URL={{ .Values.apiGateway.baseUrl | quote }}
