apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "sb.fullname" . }}-api-gateway-config
  annotations:
    "kubernetes.io/service-account.name": {{ include "sb.serviceAccountName" . }}
data:
  sm.yaml: |
    ---
    SERVER_PORT: {{ .Values.apiGateway.service.targetPort }}
    AUTH_SVC_URL: localhost:50051
    API_SVC_URL: localhost:50052
    BASE_URL: {{ .Values.api.baseUrl | quote }}
    DOC_URL: {{ .Values.api.baseUrl | quote }}
